# Generated by Django 5.0.6 on 2025-12-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Ver'), ('PDF_PREVIEW', 'Previsualizar PDF'), ('PDF_DOWNLOAD', 'Descargar PDF'), ('PDF_PRINT', 'Imprimir PDF')], max_length=20),
        ),
    ]
