# Generated by Django 5.0.6 on 2025-12-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas_app', '0003_actadefuncion_created_by_actadefuncion_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actanacimiento',
            name='distrito',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='historicalactanacimiento',
            name='distrito',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='actadefuncion',
            name='lugar_defuncion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='actadefuncion',
            name='oficial_registro',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='actamatrimonio',
            name='lugar_matrimonio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='actamatrimonio',
            name='oficial_registro',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='actanacimiento',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='actanacimiento',
            name='madre_nombre_completo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='actanacimiento',
            name='oficial_registro',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='actanacimiento',
            name='padre_nombre_completo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='actanacimiento',
            name='sexo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalactadefuncion',
            name='lugar_defuncion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalactadefuncion',
            name='oficial_registro',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalactamatrimonio',
            name='lugar_matrimonio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalactamatrimonio',
            name='oficial_registro',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalactanacimiento',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalactanacimiento',
            name='madre_nombre_completo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalactanacimiento',
            name='oficial_registro',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='historicalactanacimiento',
            name='padre_nombre_completo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalactanacimiento',
            name='sexo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
